{% macro py2dep() -%}
  - python=2.7
  - pathlib2
{% endmacro -%}
{% macro py3dep() -%}
  - python>=3.7
{% endmacro -%}
name: {{ cookiecutter.repo_name }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
  - autopep8
  - click
  - coverage
  - flake8
  - ipython
  - jedi
  - joblib
  - jupyter
  - nb_conda
  - numpy
  - pandas
  - progressbar2
  - pylint
  - pytest
  - pytest-cov
  - requests
  - scikit-learn
  - setuptools
  - sphinx
  - wheel
{% if cookiecutter.python_interpreter == 'python3' -%}
{{ py3dep()|indent(2, true) }}
{% else -%}
{{ py2dep()|indent(2, true) }}
{% endif -%}
