{% macro py2dep() -%}
  - python=2.7
  - pathlib2
{% endmacro -%}
{% macro py3dep() -%}
  - python>=3.6
{% endmacro -%}
name: {{ cookiecutter.repo_name }}
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
  - setuptools
  - wheel
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - scikit-learn
  - joblib
  - nb_conda
  - pandas
  - requests
{% if cookiecutter.python_interpreter == 'python3' -%}
{{ py3dep()|indent(2, true) }}
{% else -%}
{{ py2dep()|indent(2, true) }}
{% endif -%}
